### ISSUE TITLE
Trace on init [ Ruby 1.9 ]

### ISSUE THREAD

**Issue by acidprime** [soffes/hue#22]
``` ruby
irb(main):001:0> require 'hue'
=> true
irb(main):002:0> client = Hue::Client.new
EOFError: end of file reached
    from /opt/puppet/lib/ruby/1.9.1/net/protocol.rb:141:in `read_nonblock'
    from /opt/puppet/lib/ruby/1.9.1/net/protocol.rb:141:in `rbuf_fill'
    from /opt/puppet/lib/ruby/1.9.1/net/protocol.rb:122:in `readuntil'
    from /opt/puppet/lib/ruby/1.9.1/net/protocol.rb:132:in `readline'
    from /opt/puppet/lib/ruby/1.9.1/net/http.rb:2563:in `read_status_line'
    from /opt/puppet/lib/ruby/1.9.1/net/http.rb:2552:in `read_new'
    from /opt/puppet/lib/ruby/1.9.1/net/http.rb:1320:in `block in transport_request'
    from /opt/puppet/lib/ruby/1.9.1/net/http.rb:1317:in `catch'
    from /opt/puppet/lib/ruby/1.9.1/net/http.rb:1317:in `transport_request'
    from /opt/puppet/lib/ruby/1.9.1/net/http.rb:1294:in `request'
    from /opt/puppet/lib/ruby/1.9.1/net/http.rb:1196:in `request_get'
    from /opt/puppet/lib/ruby/1.9.1/net/http.rb:455:in `block in get_response'
    from /opt/puppet/lib/ruby/1.9.1/net/http.rb:746:in `start'
    from /opt/puppet/lib/ruby/1.9.1/net/http.rb:454:in `get_response'
    from /opt/puppet/lib/ruby/1.9.1/net/http.rb:431:in `get'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/hue-0.1.3/lib/hue/client.rb:27:in `bridges'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/hue-0.1.3/lib/hue/client.rb:19:in `bridge'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/hue-0.1.3/lib/hue/client.rb:49:in `validate_user'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/hue-0.1.3/lib/hue/client.rb:14:in `initialize'
    from (irb):2:in `new'
    from (irb):2
```

**Comment by stefangweichinger** [comment]
yep, similar here on gentoo linux:

$ hue lights 
/usr/lib64/ruby/1.9.1/net/protocol.rb:141:in `read_nonblock': end of file reached (EOFError)
	from /usr/lib64/ruby/1.9.1/net/protocol.rb:141:in `rbuf_fill'
	from /usr/lib64/ruby/1.9.1/net/protocol.rb:122:in `readuntil'
	from /usr/lib64/ruby/1.9.1/net/protocol.rb:132:in `readline'
	from /usr/lib64/ruby/1.9.1/net/http.rb:2563:in `read_status_line'
	from /usr/lib64/ruby/1.9.1/net/http.rb:2552:in `read_new'
	from /usr/lib64/ruby/1.9.1/net/http.rb:1320:in `block in transport_request'
	from /usr/lib64/ruby/1.9.1/net/http.rb:1317:in `catch'
	from /usr/lib64/ruby/1.9.1/net/http.rb:1317:in `transport_request'
	from /usr/lib64/ruby/1.9.1/net/http.rb:1294:in `request'
	from /usr/lib64/ruby/1.9.1/net/http.rb:1196:in `request_get'
	from /usr/lib64/ruby/1.9.1/net/http.rb:455:in `block in get_response'
	from /usr/lib64/ruby/1.9.1/net/http.rb:746:in `start'
	from /usr/lib64/ruby/1.9.1/net/http.rb:454:in `get_response'
	from /usr/lib64/ruby/1.9.1/net/http.rb:431:in `get'
	from /home/sgw/.gem/ruby/1.9.1/gems/hue-0.1.3/lib/hue/client.rb:27:in `bridges'
	from /home/sgw/.gem/ruby/1.9.1/gems/hue-0.1.3/lib/hue/client.rb:19:in `bridge'
	from /home/sgw/.gem/ruby/1.9.1/gems/hue-0.1.3/lib/hue/client.rb:49:in `validate_user'
	from /home/sgw/.gem/ruby/1.9.1/gems/hue-0.1.3/lib/hue/client.rb:14:in `initialize'
	from /home/sgw/.gem/ruby/1.9.1/gems/hue-0.1.3/lib/hue/cli.rb:52:in `new'
	from /home/sgw/.gem/ruby/1.9.1/gems/hue-0.1.3/lib/hue/cli.rb:52:in `client'
	from /home/sgw/.gem/ruby/1.9.1/gems/hue-0.1.3/lib/hue/cli.rb:7:in `lights'
	from /home/sgw/.gem/ruby/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/sgw/.gem/ruby/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/sgw/.gem/ruby/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/sgw/.gem/ruby/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/sgw/.gem/ruby/1.9.1/gems/hue-0.1.3/bin/hue:8:in `<top (required)>'
	from /usr/local/bin/hue:23:in `load'
	from /usr/local/bin/hue:23:in `<main>'

I am a ruby-noob ... any help someone?

**Comment by meltingice** [comment]
hue requires a minimum Ruby version of 1.9.3, is there any chance you can update?

**Comment by stefangweichinger** [comment]
gentoo allows multiple ruby-versions in parallel. Switched and reinstalled, now it works for me!
Thanks, Stefan

**Comment by soffes** [comment]
Looks like you all figured this out 9 years ago 😅
