### ISSUE TITLE
INVALID JSON - Failing to Validate User

### ISSUE THREAD

**Issue by sarkonovich** [soffes/hue#25]
All has been working fine until this morning.

Now:

client = Hue::Client.new
JSON::ParserError: A JSON text must at least contain two octets!
from /Users/arkonovs/.rvm/gems/ruby-2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `initialize'

and, from the CLI

'hue lights'   returns:

/Users/arkonovs/.rvm/gems/ruby-2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
	from /Users/arkonovs/.rvm/gems/ruby-2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `new'
	from /Users/arkonovs/.rvm/gems/ruby-2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
	from /Users/arkonovs/.rvm/gems/ruby-2.2.0/gems/json-1.8.2/lib/json/common.rb:468:in `JSON'
	from /Users/arkonovs/.rvm/gems/ruby-2.2.0/gems/hue-0.1.3/lib/hue/client.rb:27:in `bridges'
	from /Users/arkonovs/.rvm/gems/ruby-2.2.0/gems/hue-0.1.3/lib/hue/client.rb:19:in `bridge'
	from /Users/arkonovs/.rvm/gems/ruby-2.2.0/gems/hue-0.1.3/lib/hue/client.rb:49:in `validate_user'
	from /Users/arkonovs/.rvm/gems/ruby-2.2.0/gems/hue-0.1.3/lib/hue/client.rb:14:in `initialize'
	from /Users/arkonovs/GitHub/alexa-home/modules/lights.rb:4:in `new'
	from /Users/arkonovs/GitHub/alexa-home/modules/lights.rb:4:in `<top (required)>'
	from /Users/arkonovs/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/arkonovs/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from app.rb:5:in `<main>'

**Comment by sarkonovich** [comment]
It seems like Hue added a redirect to:

https://client-eastwood-dot-hue-prod-us.appspot.com/api/nupnp

from

https://www.meethue.com/api/upnp

I changed the address in client.rb and all is well again.

**Comment by soffes** [comment]
It needs to follow redirects. Need to figure it out.
