### ISSUE TITLE
Changes to Whitelist username creation

### ISSUE THREAD

**Issue by SteveyO** [soffes/hue#35]
Hi Sam,
I work for Philips Hue Developer Support.  In case you were not aware, in a few months time we will be changing the way usernames are created on the bridge (for security reasons).  Custom whitelist usernames will no longer be allowed and the bridge randomly generated username must be used instead.  Please see below link for more information:
http://www.developers.meethue.com/documentation/important-whitelist-changes

Am not a Ruby developer myself, but a quick glance at the code and in client.rb (line 97) the setting of the username will have no effect after February 2016 (the username should be derived from the bridge success response as shown in the above link) and the initialization of the username will stop working also.   Hopefully the above link should make it clear what changes need to be done here.  Apologies for the inconvenience.

Thanks
Steve

**Comment by soffes** [comment]
Thanks Steve! When can I adopt the new API?

**Comment by SteveyO** [comment]
Hi Sam,

Random bridge usernames have been in the Hue API since the beginning of Hue, so you can make the changes whenever you want and it will be fully backwards compatible.  The only thing that will change in Feb 2016 is it will no longer be able to post a custom username to create a whitelist entry.

Thanks
Steve

**Comment by soffes** [comment]
This has been added in version 0.2.0.
