### ISSUE TITLE
No Bridge Found

### ISSUE THREAD

**Issue by earlbalai** [soffes/hue#44]
Anyone know why I keep getting 
``bridge': Hue::NoBridgeFound (Hue::NoBridgeFound)`
Sometimes it works fine but most of the time it just errors

**Comment by MrChristopherWilliams** [comment]
I'm experiencing the same problem. Were you able to find a solution?

**Comment by soffes** [comment]
Sorry I haven't looked at this in years. I've been using [Home Assistant](https://home-assistant.io)'s API to control my lights instead of this gem.

If you find a solution, please feel free to open a PR!

**Comment by soffes** [comment]
Fixed in #51
